services:
  slatessh:
    build:
      context: .
      dockerfile: Dockerfile
    image: slatessh:local
    container_name: slatessh
    restart: unless-stopped
    ports:
      - "3210:3210"
    environment:
      HOST: 0.0.0.0
      PORT: 3210
      STACK_GO_DATA_DIR: /app/data
      GUACD_HOST: guacd
      GUACD_PORT: 4822
    volumes:
      - ./data:/app/data
    networks:
      - slatessh-network

  guacd:
    image: guacamole/guacd:latest
    container_name: slatessh-guacd
    networks:
      - slatessh-network
    restart: unless-stopped

networks:
  slatessh-network:
    driver: bridge
    name: slatessh-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80    
          gateway: fd01::1    

